# Docker Compose バージョン指定
version: '3.8'

services:
  spring-boot-app:
    build:
      context: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    restart: unless-stopped
