# Docker Compose バージョン指定
version: '3.8'

services:
  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    restart: unless-stopped
